builds:
- 
  env:
    - CGO_ENABLED=0
  goos:
    - windows
    - darwin
    - linux
  goarch:
    - 386
    - amd64
    - arm
    - arm64 
archives:
  -
    rlcp: true
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    files:
      - cw.bash
      - cw.zsh
      - LICENSE
      - README.md
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
brews:
  -
    name: cw
    tap:
      owner: lucagrulla
      name: homebrew-tap
    commit_author:
      name: lucagrulla
      email: luca@lucagrulla.com
    folder: Formula
    homepage: "https://www.lucagrulla.com/cw"
    description: "The best way to tail AWS Cloudwatch Logs from your terminal"
    caveats: "In order to get cw completion,
          [bash] you need to install `bash-completion` with brew.
          OR
          [zsh], add the following line to your ~/.zshrc:
            source #{HOMEBREW_PREFIX}/share/zsh/site-functions/cw.zsh"
    install: |
      bin.install "cw"

      bash_completion.install "cw.bash"
      zsh_completion.install "cw.zsh"
scoop:
  bucket:
    owner: lucagrulla
    name: cw-scoop-bucket
  homepage: "https://www.lucagrulla.com/cw"
  commit_author:
    name: lucagrulla
    email: luca@lucagrulla.com
  description: "The best way to tail AWS Cloudwatch Logs from your terminal"
  license: Apache-2.0
  persist:
    - "data"
    - "config.toml"
nfpms:
  -
    id: cw
    file_name_template: '{{ .ProjectName }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    homepage:  https://www.lucagrulla.com/cw
    description: The best way to tail AWS Cloudwatch Logs from your terminal
    maintainer: Luca Grulla luca.grulla+cw@gmail.com
    license: Apache2
    vendor: cw
    formats:
    - rpm
    dependencies:
    - git
    recommends:
    - rpm
  -
    id: cw-tail
    package_name: cw-tail  # Use the package name "cw-tail" to avoid conflicts with https://launchpad.net/ubuntu/bionic/amd64/cw
    replaces:
    - cw (<< 3.3.0)
    file_name_template: '{{ .ProjectName }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    homepage:  https://www.lucagrulla.com/cw
    description: The best way to tail AWS Cloudwatch Logs from your terminal
    maintainer: Luca Grulla luca.grulla+cw@gmail.com
    license: Apache2
    vendor: cw
    formats:
    - deb
    dependencies:
    - git

snapcrafts:
  -
    name: cw-sh
    name_template: '{{ .ProjectName }}-sh_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    summary: The best way to tail AWS Cloudwatch Logs from your terminal
    description: |
      The best way to tail AWS Cloudwatch Logs from your terminal
    grade: stable
    base: core18
    confinement: strict
    apps:
      cw:
        plugs: [network, dot-aws-config-credentials]
    plugs:
      network: 
      dot-aws-config-credentials:
        interface: personal-files
        read:
        - $HOME/.aws/config
        - $HOME/.aws/credentials
    publish: true

dockers:
- image_templates: ["lucagrulla/{{ .ProjectName }}:{{ .Version }}-i386"]
  goarch: 386
  dockerfile: Dockerfile.release
  build_flag_templates:
  - --platform=linux/386
  - --label=org.opencontainers.image.title={{ .ProjectName }}
  - --label=org.opencontainers.image.description={{ .ProjectName }}
  - --label=org.opencontainers.image.url=https://www.lucagrulla.com/cw
  - --label=org.opencontainers.image.source=https://github.com/lucagrulla/cw
  - --label=org.opencontainers.image.version={{ .Version }}
  - --label=org.opencontainers.image.revision={{ .FullCommit }}
  - --label=org.opencontainers.image.licenses=Apache-2.0
- image_templates: ["lucagrulla/{{ .ProjectName }}:{{ .Version }}-amd64"]
  goarch: amd64
  dockerfile: Dockerfile.release
  build_flag_templates:
  - --platform=linux/amd64
  - --label=org.opencontainers.image.title={{ .ProjectName }}
  - --label=org.opencontainers.image.description={{ .ProjectName }}
  - --label=org.opencontainers.image.url=https://www.lucagrulla.com/cw
  - --label=org.opencontainers.image.source=https://github.com/lucagrulla/cw
  - --label=org.opencontainers.image.version={{ .Version }}
  - --label=org.opencontainers.image.revision={{ .FullCommit }}
  - --label=org.opencontainers.image.licenses=Apache-2.0
- image_templates: ["lucagrulla/{{ .ProjectName }}:{{ .Version }}-arm64v8"]
  goarch: arm64
  dockerfile: Dockerfile.release
  build_flag_templates:
  - --platform=linux/arm64/v8
  - --label=org.opencontainers.image.title={{ .ProjectName }}
  - --label=org.opencontainers.image.description={{ .ProjectName }}
  - --label=org.opencontainers.image.url=https://www.lucagrulla.com/cw
  - --label=org.opencontainers.image.source=https://github.com/lucagrulla/cw
  - --label=org.opencontainers.image.version={{ .Version }}
  - --label=org.opencontainers.image.revision={{ .FullCommit }}
  - --label=org.opencontainers.image.licenses=Apache-2.0
docker_manifests:
- name_template: "lucagrulla/{{ .ProjectName }}:{{ .Version }}"
  image_templates:
  - lucagrulla/{{ .ProjectName }}:{{ .Version }}-i386
  - lucagrulla/{{ .ProjectName }}:{{ .Version }}-amd64
  - lucagrulla/{{ .ProjectName }}:{{ .Version }}-arm64v8
